#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -maxdepth 2 -type f -perm /111 -name 'install.sh' -exec {} \;
